#!/bin/bash


__FILE__=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`
__DIR__=$(dirname "${__FILE__}")
. $__DIR__/common.inc

NAME=rtmpdump
VERSION=2.4

do_download()
{
  info "Download $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  #rtmpdump-2.3.tgz
  if ! wget https://nos.wjv-1.neo.id/assets.juragan.biz/rtmpdump-v{VERSION}.tar.gz -O rtmpdump-${VERSION}.tar.gz; then
    error "Failed to download $NAME"
  fi
  info "Download complete"
}

do_unpack()
{
  info "Unpack $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if ! tar xzvf rtmpdump-${VERSION}.tar.gz; then
    error "Failed to unpack $NAME"
  fi
  info "Unpack complete"
}

do_configure()
{
  info "Configure $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src rtmpdump-${VERSION}
  cd librtmp
  sed -i "/INC=.*/d" ./Makefile # Remove INC if present from previous run.
  sed -i "s/prefix=.*/prefix=${BUILDDIR}\nINC=-I\$(prefix)\/include/" ./Makefile
  sed -i "s/SHARED=.*/SHARED=no/" ./Makefile
  info "Configuration complete"
}

do_compile()
{
  info "Compile $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src rtmpdump-${VERSION}
  cd librtmp
  info "Compilation complete"
}

do_install()
{
  info "Install $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src rtmpdump-${VERSION}
  cd librtmp
  if ! make install_base; then
    error "Failed to install $NAME"
  fi
  info "Installation complete"
}

do_clean()
{
  info "Clean $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src srt-${VERSION}
  if ! make clean; then
    error "Failed to clean $NAME"
  fi
  info "Clean complete"
}

main $*
